Problem.create!([
  {title: "A + B", description: "Description\n-------------\n\n Calculate A + B\n\nSample Input\n---------------\n    1 2\nSample Output\n----------\n    3\n", check_code: "???\n", judge_code: "#include <iostream>\n#include <fstream>\nusing namespace std;\nint main(int argc, char* argv[]) {\n  ifstream in(argv[1]), out(argv[2]);\n  int a, b;\n  in >> a >> b;\n  int c;\n  out >> c;\n  if (a + b == c)\n    return 0;\n  else\n    return -1;\n}\n"},
  {title: "A - B", description: "문제\n============\n\n A와 B가 주어질 때, A - B를 구하세요.\n\n\n입력 설명\n----------\n 두 개의 숫자 A, B(-10000 <= A, B <= 10000)가 입력됩니다.\n\n출력 설명\n-----------\n A - B의 값을 한 줄에 출력하세요.\n\n예제 - 입력\n------------\n    3 1\n예제 - 출력\n------------\n    2\n", check_code: "???\n", judge_code: "#include <iostream>\n#include <fstream>\nusing namespace std;\n\nint main(int args, char* argv[]){\n  ifstream in(argv[1]), out(argv[2]);\n  int a, b, c;\n  in >> a >> b;\n  out >> c;\n\n  if(a - b == c) return 0;\n  else return -1;\n}\n"},
  {title: "숫자의 합 구하기 1", description: "문제\r\n------------\r\n\r\n A와 B가 주어질 때, A부터 B까지의 모든 정수의 합을 구하세요.\r\n\r\n입력 설명\r\n------------\r\n 가장 첫 줄에는 테스트 케이스의 개수 $T$가 입력됩니다.\r\n \r\n그 뒤 _T_개의 줄에 각 테스트 케이스의 정수 $A$, $B$가 주어집니다.\r\n\r\n출력 설명\r\n-------------\r\n\r\n각 테스트 케이스마다 한 줄에 $A$부터 $B$까지의 모든 정수의 합을 출력하세요. \r\n\r\n제약조건\r\n----------\r\n\r\n$1 \\leq T \\leq 100$\r\n\r\n$1 \\leq A \\leq B \\leq 10000$\r\n\r\n예제 - 입력\r\n-------------\r\n    2\r\n    1 100\r\n    1 5\r\n\r\n예제 - 출력\r\n-------------\r\n    5050\r\n    15\r\n", check_code: "???\n", judge_code: "#include <iostream>\n#include <fstream>\nusing namespace std;\n\nint main(int args, char* argv[]){\n  ifstream in(argv[1]), out(argv[2]);\n  int tc, result = 0;\n  in >> tc;\n  while(tc-- > 0){\n    long long int a, b, ans, submit;\n    in >> a >> b;\n    out >> submit;\n\n    ans = b * (b + 1) / 2 - a * (a + 1) / 2 + a;\n    if(submit == ans) continue;\n    else {result = -1; break;}\n  }\n  return result;\n}\n"},
  {title: "계산기 만들기 1", description: "문제\r\n------\r\n\r\n두 개의 숫자와 연산자가 주어질 때, 해당 연산의 결과를 구하세요. \r\n연산자는 모두 다섯 개이며 각 기호의 의미는 다음과 같습니다.\r\n\r\n| 연산자    | 정의                        |\r\n| -------  |:---------------------------|\r\n| `A + B`  |                  A와 B의 합|\r\n| `A - B`  |              A에서 B를 뺀 차 |\r\n| `A * B`  |                  A와 B의 곱 |\r\n| `A / B`  |       A를 B로 나누었을 때의 몫 |\r\n| `A % B`  |     A를 B로 나누었을 때의 나머지 |\r\n\r\n입력 설명\r\n-------------------\r\n가장 첫 줄에는 테스트 케이스의 개수 $T$가 입력됩니다.\r\n\r\n그 뒤 T개의 줄에 각 테스트 케이스의 정수 $A$, $B$와 연산자가 주어집니다.\r\n\r\n출력 설명\r\n-------------\r\n각 테스트 케이스마다 한 줄에 연산의 결과를 출력하세요.\r\n\r\n연산이 불가능할 경우 따옴표를 제외한 `Impossible`을 출력하세요.\r\n제약 조건\r\n-----------\r\n$1 \\leq T \\leq 100$\r\n\r\n$-10000 \\leq A \\leq B \\leq 10000$\r\n\r\n예제 - 입력\r\n-------------\r\n    5\r\n    7 3 +\r\n    7 3 -\r\n    7 3 *\r\n    7 3 /\r\n    7 3 %\r\n예제 - 출력\r\n-------------\r\n    10\r\n    4\r\n    21\r\n    2\r\n    1", check_code: "???\n", judge_code: "#include <stdio.h>\n#include <string.h>\n\nint main(int argc, char* argv[]){\n  FILE* in = fopen(argv[1], \"r\");\n  FILE* out = fopen(argv[2], \"r\");\n\n  int tc, result = 0;\n  fscanf(in, \"%d\", &tc);\n  while(tc-- > 0){\n    int a, b, ans;\n    char c;\n    fscanf(in, \"%d %d %c\", &a, &b, &c);\n\n    if(b == 0 && (c == '/' || c == '%')){\n      char submit[12];\n      fscanf(out, \"%s\", submit);\n      if(strcmp(submit, \"Impossible\") == 0) continue;\n      else {result = -1; break;}\n    }\n\n    if(c == '+') ans = a + b;\n    else if(c == '-') ans = a - b;\n    else if(c == '*') ans = a * b;\n    else if(c == '/') ans = a / b;\n    else ans = a % b;\n\n    int submit;\n    fscanf(out, \"%d\", &submit);\n    if(submit == ans) continue;\n    else {result = -1; break;}\n  }\n  return result;\n}\n"}
])
SystemTest.create!([
  {input_data: "10 20\n", problem_id: 1},
  {input_data: "1 2\n", problem_id: 1},
  {input_data: "20 10", problem_id: 2},
  {input_data: "2\r\n1 100\r\n-5 5", problem_id: 3},
  {input_data: "    5\r\n    7 3 +\r\n    7 3 -\r\n    7 3 *\r\n    7 3 /\r\n    7 3 %", problem_id: 4}
])
